#!/bin/bash

### BEGIN INIT INFO
# Provides:          cflora
# Required-Start:    mysql
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable cflora service provided by daemon.
### END INIT INFO

WORK_DIR="/usr/local/cflora/bin"

case "$1" in
  start)
    echo "Starting server"
    cd "$WORK_DIR"
	./cflora-run.sh
	./cflora-mon.sh & > /dev/null
    #$DAEMON start
    ;;
  stop)
    echo "Stopping server"
    cd "$WORK_DIR"
	./cflora-stop.sh
    #$DAEMON stop
    ;;
  *)
    echo "Usage: /etc/init.d/cflora {start|stop}"
    exit 1
    ;;
esac
exit 0
